import { describe, expect, it } from 'vitest';
import { computeFixedBeezioPlatformFee } from './beezioFee';
import { computeFixedTierPricing } from './customerPrice';

describe('fixed-tier Beezio pricing contract', () => {
  it.each([0.01, 19.99, 25, 50, 100, 200, 500])('charges a flat $2 platform allocation at $%s', price => expect(computeFixedBeezioPlatformFee(price)).toBe(2));
  it('does not charge on a zero price', () => expect(computeFixedBeezioPlatformFee(0)).toBe(0));
  it('keeps the platform fee flat when the final price crosses $100',()=>{const result=computeFixedTierPricing({sellerPayout:93,affiliatePayout:0,shippingIncluded:0});expect(result.finalAdvertisedPrice).toBe(101.66);expect(result.platformFee).toBe(2);expect(result.influencerAllocation).toBe(2);expect(result.paypalProcessingAllowance).toBe(4.66);expect(result.iterations).toBeGreaterThan(1);});
  it('keeps seller, affiliate, and shipping buckets whole',()=>{const result=computeFixedTierPricing({supplierCost:23.8,sellerMarkup:10,affiliatePayout:5,shippingIncluded:6.2,estimatedTaxRate:0.07});expect(result.sellerPayout).toBe(33.8);expect(result.affiliatePayout).toBe(5);expect(result.shippingIncluded).toBe(6.2);expect(result.finalAdvertisedPrice).toBe(51.67);expect(result.platformFee).toBe(2);expect(result.influencerAllocation).toBe(2);expect(result.paypalProcessingAllowance).toBe(2.67);expect(result.estimatedSalesTax).toBe(3.62);expect(result.estimatedCheckoutTotal).toBe(55.29);});
  it('reserves $2 of platform revenue on inexpensive products',()=>{const result=computeFixedTierPricing({sellerPayout:10,affiliatePayout:0,shippingIncluded:0});expect(result.finalAdvertisedPrice).toBeLessThan(25);expect(result.platformFee).toBe(2);expect(result.influencerAllocation).toBe(1);});
  it('does not count an unused influencer allocation as Beezio profit',()=>{const result=computeFixedTierPricing({sellerPayout:10});expect(result.platformFee).toBe(2);expect(result.platformFee).not.toBe(result.platformFee+result.influencerAllocation);});
  it('allows the seller to offer an affiliate payout larger than the seller payout',()=>{const result=computeFixedTierPricing({supplierCost:4,sellerMarkup:1,affiliatePayout:8});expect(result.sellerPayout).toBe(5);expect(result.affiliatePayout).toBe(8);expect(result.finalAdvertisedPrice).toBeGreaterThanOrEqual(15);});
  it('does not enforce markup or affiliate minimums',()=>{const result=computeFixedTierPricing({supplierCost:4,sellerMarkup:0,affiliatePayout:0});expect(result.sellerMarkup).toBe(0);expect(result.affiliatePayout).toBe(0);});
  it('uses $1 total influencer allocation only when the settled price is under $20',()=>{const under=computeFixedTierPricing({sellerPayout:10});const crossed=computeFixedTierPricing({sellerPayout:17});expect(under.finalAdvertisedPrice).toBe(14.17);expect(under.influencerAllocation).toBe(1);expect(under.influencerPerSlot).toBe(0.5);expect(crossed.finalAdvertisedPrice).toBeGreaterThanOrEqual(20);expect(crossed.influencerAllocation).toBe(2);expect(crossed.influencerPerSlot).toBe(1);});
});
