import { describe, expect, it } from 'vitest';
import { computeFixedBeezioPlatformFee } from './beezioFee';
import { computeFixedTierPricing } from './customerPrice';

describe('fixed-tier Beezio pricing contract', () => {
  it.each([[0.01,1],[15,1],[15.01,2],[50,2],[50.01,3],[75,3],[75.01,4],[100,4],[100.01,5],[125,5],[125.01,6],[250,10],[500,20],[1000,40]])('seller ask $%s reserves $%s', (ask, fee) => expect(computeFixedBeezioPlatformFee(ask)).toBe(fee));
  it('does not charge on a zero price', () => expect(computeFixedBeezioPlatformFee(0)).toBe(0));
  it('uses seller ask rather than the final buyer price for brackets',()=>{const result=computeFixedTierPricing({sellerPayout:93,affiliatePayout:0,shippingIncluded:0});expect(result.finalAdvertisedPrice).toBe(103.74);expect(result.platformFee).toBe(4);expect(result.influencerAllocation).toBe(2);expect(result.paypalProcessingAllowance).toBe(4.74);expect(result.iterations).toBeGreaterThan(1);});
  it('keeps seller, affiliate, and shipping buckets whole',()=>{const result=computeFixedTierPricing({supplierCost:23.8,sellerMarkup:10,affiliatePayout:5,shippingIncluded:6.2,estimatedTaxRate:0.07});expect(result.sellerPayout).toBe(33.8);expect(result.affiliatePayout).toBe(5);expect(result.shippingIncluded).toBe(6.2);expect(result.finalAdvertisedPrice).toBe(51.67);expect(result.platformFee).toBe(2);expect(result.influencerAllocation).toBe(2);expect(result.paypalProcessingAllowance).toBe(2.67);expect(result.estimatedSalesTax).toBe(3.62);expect(result.estimatedCheckoutTotal).toBe(55.29);});
  it('reserves $1 of platform revenue on inexpensive products',()=>{const result=computeFixedTierPricing({sellerPayout:10,affiliatePayout:0,shippingIncluded:0});expect(result.finalAdvertisedPrice).toBeLessThan(25);expect(result.platformFee).toBe(1);expect(result.influencerAllocation).toBe(1);});
  it('does not count an unused influencer allocation as Beezio profit',()=>{const result=computeFixedTierPricing({sellerPayout:10});expect(result.platformFee).toBe(1);expect(result.platformFee).not.toBe(result.platformFee+result.influencerAllocation);});
  it('allows the seller to offer an affiliate payout larger than the seller payout',()=>{const result=computeFixedTierPricing({supplierCost:4,sellerMarkup:1,affiliatePayout:8});expect(result.sellerPayout).toBe(5);expect(result.affiliatePayout).toBe(8);expect(result.finalAdvertisedPrice).toBeGreaterThanOrEqual(15);});
  it.each([[14.20,5.99,4.10],[12.20,7.99,2.10]])('prices shirts at $29.99 with seller ask %s', (ask, shipping, margin) => { const result = computeFixedTierPricing({supplierCost:10.10,sellerMarkup:margin,sellerPayout:ask,affiliatePayout:5,shippingIncluded:shipping}); expect(result.finalAdvertisedPrice).toBe(29.99); expect(result.platformFee).toBe(1); expect(result.affiliatePayout).toBe(5); expect(result.influencerAllocation).toBe(2); expect(result.paypalProcessingAllowance).toBe(1.80); expect(Math.round((ask+5+shipping+result.platformFee+result.influencerAllocation+result.paypalProcessingAllowance)*100)).toBe(2999); });
  it('does not enforce markup or affiliate minimums',()=>{const result=computeFixedTierPricing({supplierCost:4,sellerMarkup:0,affiliatePayout:0});expect(result.sellerMarkup).toBe(0);expect(result.affiliatePayout).toBe(0);});
  it('uses $1 total influencer allocation only when the settled price is under $20',()=>{const under=computeFixedTierPricing({sellerPayout:10});const crossed=computeFixedTierPricing({sellerPayout:17});expect(under.finalAdvertisedPrice).toBe(13.13);expect(under.influencerAllocation).toBe(1);expect(under.influencerPerSlot).toBe(0.5);expect(crossed.finalAdvertisedPrice).toBeGreaterThanOrEqual(20);expect(crossed.influencerAllocation).toBe(2);expect(crossed.influencerPerSlot).toBe(1);});
});
