import { createClient } from '@supabase/supabase-js';

export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
export const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'placeholder-key';

// Log configuration status for debugging
if (supabaseUrl === 'https://placeholder.supabase.co' || supabaseAnonKey === 'placeholder-key') {
  console.warn('Supabase not configured. Please create a .env file with your Supabase credentials.');
}

export const isSupabaseConfigured = (
  supabaseUrl !== 'https://placeholder.supabase.co' &&
  supabaseAnonKey !== 'placeholder-key'
);

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          full_name: string;
          role: 'buyer' | 'seller' | 'affiliate' | 'admin';
          primary_role?: 'buyer' | 'seller' | 'affiliate' | 'admin' | null;
          referred_by_affiliate_id?: string | null;
          avatar_url?: string;
          bio?: string;
          website?: string;
          location?: string;
          street_address?: string | null;
          city?: string | null;
          state?: string | null;
          country?: string | null;
          phone?: string;
          zip_code?: string;
          payment_customer_id?: string;
          payment_account_id?: string;
          sale_email_notifications?: boolean;
          created_at: string;
          updated_at: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          description?: string;
          icon_name?: string;
          slug: string;
          parent_id?: string;
          created_at: string;
        };
      };
        products: {
          Row: {
            id: string;
            seller_id: string;
            category_id?: string;
            beezio_category_id?: string | null;
            cj_product_id?: string | null;
            source?: string | null;
            cj_pid?: string | null;
            cj_product_code?: string | null;
            cj_product_sku?: string | null;
            cj_spu?: string | null;
            cj_name_raw?: string | null;
            cj_source_payload_json?: Record<string, unknown> | null;
            searchable_codes?: string[] | null;
            import_status?: 'ready' | 'needs_review' | null;
            legacy_code?: string | null;
            display_search_code?: string | null;
            source_import_version?: string | null;
            status?: 'draft' | 'active' | 'archived' | null;
            title: string;
            description?: string;
            primary_image_url?: string | null;
          // Product lineage / source: affects fulfillment, fees, etc.
          // Backed by a text/varchar column in the products table.
          // Expected values (non-exhaustive):
          // - 'CJ'            → imported from CJ dropshipping
          // - 'SELLER_DIRECT' → manually added by a seller
          // - 'BEEZIO_HOUSE'  → Beezio-owned products
          lineage?: 'CJ' | 'SELLER_DIRECT' | 'BEEZIO_HOUSE' | string | null;
          price: number;
          seller_ask?: number | null;
          seller_amount?: number | null;
          seller_ask_price?: number | null;
            currency?: string | null;
            images: string[];
            base_weight_oz?: number | null;
            package_length_in?: number | null;
            package_width_in?: number | null;
            package_height_in?: number | null;
            base_cost_cents?: number | null;
            retail_price_cents?: number | null;
            shipping_estimate_cents?: number | null;
            affiliate_percent?: number | null;
            affiliate_floor_cents?: number | null;
            markup_type?: 'flat' | 'percent' | null;
            markup_value?: number | null;
            paypal_fee_bps?: number | null;
            paypal_fixed_cents?: number | null;
            track_inventory?: boolean | null;
            in_stock?: boolean | null;
            total_inventory?: number | null;
            stock_quantity: number;
            is_active: boolean;
          is_subscription?: boolean | null;
          subscription_interval?: string | null;
          subscription_price?: number | null;
          affiliate_enabled?: boolean;
          commission_rate: number;
          commission_type: 'percentage' | 'flat_rate';
          flat_commission_amount: number;
          affiliate_commission_type?: 'percent' | 'flat';
          affiliate_commission_value?: number | null;
          calculated_customer_price?: number | null;
          sample_enabled?: boolean | null;
          sample_price?: number | null;
          shipping_cost: number;
          shipping_price?: number | null;
          is_digital?: boolean | null;
          digital_download_bucket?: string | null;
          digital_download_path?: string | null;
          digital_download_filename?: string | null;
          digital_download_content_type?: string | null;
          digital_download_file_size?: number | null;
          digital_download_instructions?: string | null;
          digital_download_limit?: number | null;
          digital_return_policy_notice?: string | null;
          tags: string[];
          videos: string[];
          unique_slug?: string;
          views_count: number;
          clicks_count: number;
          conversions_count: number;
          created_at: string;
          updated_at: string;
        };
      };
      product_variants: {
        Row: {
          id: string;
          product_id: string;
          provider: string;
          source?: string | null;
          cj_product_id: string | null;
          cj_variant_id: string | null;
          cj_vid?: string | null;
          cj_variant_sku?: string | null;
          cj_variant_code?: string | null;
          cj_sku?: string | null;
          cj_option_summary?: string | null;
          supplier_variant_ref?: string | null;
          external_inventory_key?: string | null;
          variant_display_sku?: string | null;
          searchable_codes?: string[] | null;
          is_orderable?: boolean | null;
          order_reference_type?: 'cj_vid' | 'cj_variant_id' | 'none' | null;
          raw_variant_payload_json?: Record<string, unknown> | null;
          import_status?: 'ready' | 'needs_review' | null;
          legacy_code?: string | null;
          sku: string;
          price: number;
          compare_at_price: number | null;
          currency: string;
          image_url: string | null;
          attributes: Record<string, string> | null;
          inventory: number | null;
          is_active: boolean;
          source_platform?: string | null;
          external_product_id?: string | null;
          external_variant_id?: string | null;
          external_data?: Record<string, unknown> | null;
          option1_name?: string | null;
          option1_value?: string | null;
          option2_name?: string | null;
          option2_value?: string | null;
          option3_name?: string | null;
          option3_value?: string | null;
          weight_oz?: number | null;
          cost_cents?: number | null;
          retail_price_cents?: number | null;
          inventory_policy?: 'deny' | 'continue' | null;
          in_stock?: boolean | null;
          inventory_source?: 'manual' | 'cj' | 'printful' | 'printify' | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          provider?: string;
          source?: string | null;
          cj_product_id?: string | null;
          cj_variant_id?: string | null;
          cj_vid?: string | null;
          cj_variant_sku?: string | null;
          cj_variant_code?: string | null;
          cj_sku?: string | null;
          cj_option_summary?: string | null;
          supplier_variant_ref?: string | null;
          external_inventory_key?: string | null;
          variant_display_sku?: string | null;
          searchable_codes?: string[] | null;
          is_orderable?: boolean | null;
          order_reference_type?: 'cj_vid' | 'cj_variant_id' | 'none' | null;
          raw_variant_payload_json?: Record<string, unknown> | null;
          import_status?: 'ready' | 'needs_review' | null;
          legacy_code?: string | null;
          sku: string;
          price: number;
          compare_at_price?: number | null;
          currency?: string;
          image_url?: string | null;
          attributes?: Record<string, string> | null;
          inventory?: number | null;
          is_active?: boolean;
          source_platform?: string | null;
          external_product_id?: string | null;
          external_variant_id?: string | null;
          external_data?: Record<string, unknown> | null;
          option1_name?: string | null;
          option1_value?: string | null;
          option2_name?: string | null;
          option2_value?: string | null;
          option3_name?: string | null;
          option3_value?: string | null;
          weight_oz?: number | null;
          cost_cents?: number | null;
          retail_price_cents?: number | null;
          inventory_policy?: 'deny' | 'continue' | null;
          in_stock?: boolean | null;
          inventory_source?: 'manual' | 'cj' | 'printful' | 'printify' | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          provider?: string;
          source?: string | null;
          cj_product_id?: string | null;
          cj_variant_id?: string | null;
          cj_vid?: string | null;
          cj_variant_sku?: string | null;
          cj_variant_code?: string | null;
          cj_sku?: string | null;
          cj_option_summary?: string | null;
          supplier_variant_ref?: string | null;
          external_inventory_key?: string | null;
          variant_display_sku?: string | null;
          searchable_codes?: string[] | null;
          is_orderable?: boolean | null;
          order_reference_type?: 'cj_vid' | 'cj_variant_id' | 'none' | null;
          raw_variant_payload_json?: Record<string, unknown> | null;
          import_status?: 'ready' | 'needs_review' | null;
          legacy_code?: string | null;
          sku?: string;
          price?: number;
          compare_at_price?: number | null;
          currency?: string;
          image_url?: string | null;
          attributes?: Record<string, string> | null;
          inventory?: number | null;
          is_active?: boolean;
          source_platform?: string | null;
          external_product_id?: string | null;
          external_variant_id?: string | null;
          external_data?: Record<string, unknown> | null;
          option1_name?: string | null;
          option1_value?: string | null;
          option2_name?: string | null;
          option2_value?: string | null;
          option3_name?: string | null;
          option3_value?: string | null;
          weight_oz?: number | null;
          cost_cents?: number | null;
          retail_price_cents?: number | null;
          inventory_policy?: 'deny' | 'continue' | null;
          in_stock?: boolean | null;
          inventory_source?: 'manual' | 'cj' | 'printful' | 'printify' | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      cj_products: {
        Row: {
          cj_product_id: string;
          raw_json: Record<string, unknown>;
          imported_at: string;
        };
      };
      category_map_cj_to_beezio: {
        Row: {
          cj_category_path: string;
          beezio_category_id: string | null;
          fallback: boolean;
        };
      };
      pricing_rules: {
        Row: {
          beezio_category_id: string;
          affiliate_percent: number;
          affiliate_floor_cents: number;
          affiliate_enabled: boolean;
          markup_type: 'flat' | 'percent';
          markup_value: number;
          paypal_fee_bps: number;
          paypal_fixed_cents: number;
        };
      };
      shipping_rules: {
        Row: {
          id: string;
          name: string;
          tiers_json: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          actor_user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string;
          details: Record<string, unknown>;
          created_at: string;
        };
      };
      shipping_options: {
        Row: {
          id: string;
          product_id: string;
          variant_id: string | null;
          provider: string;
          destination_country: string;
          method_code: string;
          method_name: string;
          cost: number;
          min_days: number | null;
          max_days: number | null;
          processing_days: number | null;
          last_quoted_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          variant_id?: string | null;
          provider?: string;
          destination_country: string;
          method_code: string;
          method_name: string;
          cost: number;
          min_days?: number | null;
          max_days?: number | null;
          processing_days?: number | null;
          last_quoted_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          variant_id?: string | null;
          provider?: string;
          destination_country?: string;
          method_code?: string;
          method_name?: string;
          cost?: number;
          min_days?: number | null;
          max_days?: number | null;
          processing_days?: number | null;
          last_quoted_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      affiliate_stores: {
        Row: {
          id: string;
          profile_id: string;
          store_name: string;
          store_slug: string;
          description: string;
          logo_url?: string;
          banner_url?: string;
          custom_domain?: string;
          is_active: boolean;
          theme_color: string;
          created_at: string;
          updated_at: string;
        };
      };
      affiliate_store_products: {
        Row: {
          id: string;
          store_id: string;
          product_id: string;
          added_at: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string | null;
          product_id: string | null;
          seller_id: string | null;
          affiliate_id?: string | null;
          affiliate_referrer_id?: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          sale_price?: number | null;
          seller_payout?: number | null;
          affiliate_commission?: number | null;
          referral_bonus?: number | null;
          beezio_gross?: number | null;
          beezio_net?: number | null;
          processing_fee?: number | null;
          commission_rate?: number | null;
          affiliate_commission_rate?: number | null;
          variant_id?: string | null;
          shipping_option_id?: string | null;
          title_snapshot?: string | null;
          attributes_snapshot?: Record<string, unknown> | null;
          cj_product_id?: string | null;
          cj_variant_id?: string | null;
          source_platform?: string | null;
          external_product_id?: string | null;
          external_variant_id?: string | null;
          sku?: string | null;
          shipping_cost?: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          product_id?: string | null;
          seller_id?: string | null;
          affiliate_id?: string | null;
          affiliate_referrer_id?: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          sale_price?: number | null;
          seller_payout?: number | null;
          affiliate_commission?: number | null;
          referral_bonus?: number | null;
          beezio_gross?: number | null;
          beezio_net?: number | null;
          processing_fee?: number | null;
          commission_rate?: number | null;
          affiliate_commission_rate?: number | null;
          variant_id?: string | null;
          shipping_option_id?: string | null;
          title_snapshot?: string | null;
          attributes_snapshot?: Record<string, unknown> | null;
          cj_product_id?: string | null;
          cj_variant_id?: string | null;
          source_platform?: string | null;
          external_product_id?: string | null;
          external_variant_id?: string | null;
          sku?: string | null;
          shipping_cost?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          product_id?: string | null;
          seller_id?: string | null;
          affiliate_id?: string | null;
          affiliate_referrer_id?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          sale_price?: number | null;
          seller_payout?: number | null;
          affiliate_commission?: number | null;
          referral_bonus?: number | null;
          beezio_gross?: number | null;
          beezio_net?: number | null;
          processing_fee?: number | null;
          commission_rate?: number | null;
          affiliate_commission_rate?: number | null;
          variant_id?: string | null;
          shipping_option_id?: string | null;
          title_snapshot?: string | null;
          attributes_snapshot?: Record<string, unknown> | null;
          cj_product_id?: string | null;
          cj_variant_id?: string | null;
          source_platform?: string | null;
          external_product_id?: string | null;
          external_variant_id?: string | null;
          sku?: string | null;
          shipping_cost?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      digital_download_entitlements: {
        Row: {
          id: string;
          order_id: string;
          order_item_id: string;
          product_id: string;
          seller_id?: string | null;
          buyer_user_id?: string | null;
          billing_email?: string | null;
          storage_bucket: string;
          storage_path: string;
          original_filename: string;
          content_type?: string | null;
          file_size_bytes?: number | null;
          download_limit: number;
          download_count: number;
          last_downloaded_at?: string | null;
          access_status: string;
          metadata?: Record<string, unknown> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          order_item_id: string;
          product_id: string;
          seller_id?: string | null;
          buyer_user_id?: string | null;
          billing_email?: string | null;
          storage_bucket: string;
          storage_path: string;
          original_filename: string;
          content_type?: string | null;
          file_size_bytes?: number | null;
          download_limit?: number;
          download_count?: number;
          last_downloaded_at?: string | null;
          access_status?: string;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          order_item_id?: string;
          product_id?: string;
          seller_id?: string | null;
          buyer_user_id?: string | null;
          billing_email?: string | null;
          storage_bucket?: string;
          storage_path?: string;
          original_filename?: string;
          content_type?: string | null;
          file_size_bytes?: number | null;
          download_limit?: number;
          download_count?: number;
          last_downloaded_at?: string | null;
          access_status?: string;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number?: string | null;
          user_id?: string | null;
          affiliate_id?: string | null;
          store_id?: string | null;
          total_amount?: number | null;
          shipping_total?: number | null;
          shipping_amount?: number | null;
          currency?: string | null;
          status?: string | null;
          payment_status?: string | null;
          payment_reference_id?: string | null;
          billing_name?: string | null;
          billing_email?: string | null;
          shipping_address?: Record<string, unknown> | null;
          cj_order_id?: string | null;
          cj_tracking_number?: string | null;
          cj_tracking_url?: string | null;
          shipping_option_id?: string | null;
          order_items?: unknown | null;
          created_at: string;
          updated_at?: string | null;
        };
        Insert: {
          id?: string;
          order_number?: string | null;
          user_id?: string | null;
          affiliate_id?: string | null;
          store_id?: string | null;
          total_amount?: number | null;
          shipping_total?: number | null;
          shipping_amount?: number | null;
          currency?: string | null;
          status?: string | null;
          payment_status?: string | null;
          payment_reference_id?: string | null;
          billing_name?: string | null;
          billing_email?: string | null;
          shipping_address?: Record<string, unknown> | null;
          cj_order_id?: string | null;
          cj_tracking_number?: string | null;
          cj_tracking_url?: string | null;
          shipping_option_id?: string | null;
          order_items?: unknown | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string | null;
          user_id?: string | null;
          affiliate_id?: string | null;
          store_id?: string | null;
          total_amount?: number | null;
          shipping_total?: number | null;
          shipping_amount?: number | null;
          currency?: string | null;
          status?: string | null;
          payment_status?: string | null;
          payment_reference_id?: string | null;
          billing_name?: string | null;
          billing_email?: string | null;
          shipping_address?: Record<string, unknown> | null;
          cj_order_id?: string | null;
          cj_tracking_number?: string | null;
          cj_tracking_url?: string | null;
          shipping_option_id?: string | null;
          order_items?: unknown | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_roles: {
        Row: {
          id: string;
          user_id: string;
          role: 'buyer' | 'seller' | 'affiliate' | 'admin';
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
      };
      influencer_referrals: {
        Row: {
          id: string;
          recruited_profile_id: string;
          recruited_role: 'seller' | 'affiliate';
          influencer_profile_id: string;
          created_at: string;
          updated_at: string;
        };
      };
    };
  };
};
